name: fire
description: "A new Flutter project."
#
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.4
  table_calendar: ^3.0.0
  fl_chart: 0.36.0
  carousel_slider: ^5.0.0
  firebase_core: ^3.5.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  provider: ^6.1.2
  firebase_ui_auth: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/Group1.png
    - assets/Asset1.png
    - assets/Frame.png
    - assets/Young.png
    - assets/logo.png
    - assets/Group.png
    - assets/Frame1.png
    - assets/Frame241.png
    - assets/Math.png
    - assets/Science.png
    - assets/Social.png
    - assets/Computer.png
    - assets/scienceChem.png
    - assets/Eng.png
    - assets/Account.png
    - assets/Attendance.png
    - assets/chat.png
    - assets/routine.png
    - assets/dashboard.png
    - assets/FeeIcon.png
    - assets/leave.png
    - assets/library.png
    - assets/NoticeIcon.png
    - assets/notification.png
    - assets/profile.png
    - assets/subjects.png
    - assets/chat.png
    - assets/parents.png
    - assets/ApplyLeave.png
    - assets/eLibrary.png
    - assets/event.png
    - assets/Teacher.png
    - assets/result.png
    - assets/chat1.png
    - assets/Attendance1.png
    - assets/Money.png
    - assets/Abhilish.png
    - assets/Amila.png
    - assets/Call.png
    - assets/Kshinu.png
    - assets/Sarbin.png
    - assets/Rhitin.png
    - assets/gallery_image_2.png
    - assets/gallery_image_3.png
    - assets/gallery_image_1.png
    - assets/gallery_image_0.png
    - assets/class.png
    - assets/Calendar.png
    - assets/BloodGroup.png
    - assets/Gender.png
    - assets/relationship.png
    - assets/address.png
    - assets/occupation.png
    - assets/father.png
    - assets/phone.png
    - assets/guardian.png
    - assets/mother.png
    - assets/homework.png
    - assets/addWork.png
    - assets/SocialStd.png
    - assets/Nepali.png
    - assets/Mathematics.png
    - assets/History.png
    - assets/English.png
    - assets/ComputerSub.png
    - assets/Filter.png
    - assets/Expertise.png
    - assets/Experience.png
    - assets/UserName.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
