// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fihkKtTH6eQnG6OFlAf9IrdVljRKPYg',
    appId: '1:587467055475:web:196356b59771d9d3322506',
    messagingSenderId: '587467055475',
    projectId: 'fire-2dfaa',
    authDomain: 'fire-2dfaa.firebaseapp.com',
    storageBucket: 'fire-2dfaa.appspot.com',
    measurementId: 'G-SHPYL9FBB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAznMcfSl2qAsgfM62bXDvbNG_nqRLpQpM',
    appId: '1:587467055475:android:55e94307b4dee20b322506',
    messagingSenderId: '587467055475',
    projectId: 'fire-2dfaa',
    storageBucket: 'fire-2dfaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUBxAyqNlSezF2Jwp6dWdK7dedoIMncGU',
    appId: '1:587467055475:ios:edd5625a121ef22d322506',
    messagingSenderId: '587467055475',
    projectId: 'fire-2dfaa',
    storageBucket: 'fire-2dfaa.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUBxAyqNlSezF2Jwp6dWdK7dedoIMncGU',
    appId: '1:587467055475:ios:edd5625a121ef22d322506',
    messagingSenderId: '587467055475',
    projectId: 'fire-2dfaa',
    storageBucket: 'fire-2dfaa.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3fihkKtTH6eQnG6OFlAf9IrdVljRKPYg',
    appId: '1:587467055475:web:021ca98e3427d6ba322506',
    messagingSenderId: '587467055475',
    projectId: 'fire-2dfaa',
    authDomain: 'fire-2dfaa.firebaseapp.com',
    storageBucket: 'fire-2dfaa.appspot.com',
    measurementId: 'G-GX1VKF8CDX',
  );

}